Update landscape.yml
lfnetworking/member_landscape pull request #504
Opened 2024-07-17 20:36 UTC by mrsjackson76

Adding CNTi to LFN

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

2024-07-17 20:38 UTC, lfn-github commented
<pre>Build failed because of:
bad indentation of a mapping entry (26:15)

 23 |               - repo_url: https://github.com/ ...
 24 |               - repo_url: https://github.com/ ...
 25 |               - repo_url: https://github.com/ ...
 26 |               name: CNTi
--------------------^
 27 |             allow_duplicate_repo: true
 28 |             homepage_url: https://lfnetworkin ...</pre>

2024-07-18 18:30 UTC, lfn-github commented
<pre>Build failed because of:
bad indentation of a mapping entry (26:15)

 23 |               - repo_url: https://github.com/ ...
 24 |               - repo_url: https://github.com/ ...
 25 |               - repo_url: https://github.com/ ...
 26 |               name: CNTi
--------------------^
 27 |             allow_duplicate_repo: true
 28 |             homepage_url: https://lfnetworkin ...</pre>

2024-07-18 21:19 UTC, lfn-github commented
<pre>Build failed because of:
bad indentation of a mapping entry (510:10)

 507 |             description: &gt;
 508 |               The Nephio project is buil ...
 509 |               as 5G Network Functions, a ...
 510 |          - item:
----------------^
 511 |           name: Paraglider
 512 |             allow_duplicate_repo: true</pre>

2024-07-18 21:30 UTC, lfn-github commented
<pre>Build failed because of:
bad indentation of a mapping entry (510:10)

 507 |             description: &gt;
 508 |               The Nephio project is buil ...
 509 |               as 5G Network Functions, a ...
 510 |          - item:
----------------^
 511 |            name: Paraglider
 512 |             allow_duplicate_repo: true</pre>

2024-07-18 21:38 UTC, bramwelt requested changes

2024-07-18 21:38 UTC, bramwelt commented on landscape.yml
> +           name: Paraglider
```suggestion
          - item:
            name: Paraglider
```

2024-07-18 21:38 UTC, bramwelt commented on landscape.yml
> +           Paraglider is a cross-cloud control plane for configuring cloud networks.
```suggestion
            description: |
            Paraglider is a cross-cloud control plane for configuring cloud networks.
```

2024-07-18 21:42 UTC, lfn-github commented
<pre>Build failed because of:
bad indentation of a sequence entry (510:9)

 507 |             description: &gt;
 508 |               The Nephio project is bui ...
 509 |               as 5G Network Functions,  ...
 510 |         - item:
---------------^
 511 |           name: Paraglider
 512 |             allow_duplicate_repo: true</pre>

2024-07-24 14:41 UTC, lfn-github commented
<pre>Build failed because of:
bad indentation of a mapping entry (510:10)

 507 |             description: &gt;
 508 |               The Nephio project is buil ...
 509 |               as 5G Network Functions, a ...
 510 |          - item:
----------------^
 511 |            name: Paraglider
 512 |            allow_duplicate_repo: true</pre>

2024-07-24 15:45 UTC, lfn-github commented
<pre>Build failed because of:
No cached entry, and Paraglider has issues with logo: logos/paraglider-logo.svg, ENOENT: no such file or directory, open &#39;/opt/build/repo/hosted_logos/logos/paraglider-logo.svg&#39;
No cached entry, and CNTi has issues with logo: logos/CNTi_logo_COLOR.svg, ENOENT: no such file or directory, open &#39;/opt/build/repo/hosted_logos/logos/CNTi_logo_COLOR.svg&#39;
Item CNTi has no image_data
Item Paraglider has no image_data</pre>

2024-07-25 20:37 UTC, bramwelt requested changes
Hey @mrsjackson76 , last this is the `logo:` reference should include just the filename: no `logo/` prefix is needed.

2024-07-25 20:37 UTC, bramwelt commented on landscape.yml
> +            logo: logos/CNTi_logo_COLOR.svg
```suggestion
            logo: CNTi_logo_COLOR.svg
```

2024-07-25 20:37 UTC, bramwelt commented on landscape.yml
> +            logo: logos/paraglider-logo.svg
```suggestion
            logo: paraglider-logo.svg
```

2024-07-29 19:08 UTC, bramwelt approved these changes

2024-07-29 19:08 UTC, merged